### ISSUE TITLE
Severe chronic rhinosinusitis is an inflammatory condition of the sinuses in which symptoms last 12 weeks or longer.

### ISSUE THREAD

**Issue by notsewspokensimpaLE** [notsewspokensimpaLE/Bring#2]
https://www.google.com/collections/s/list/4619JyR_4Pv4KOVL10t3Mca2DQOj6Q/AjxyCic_jno

**Comment by notsewspokensimpaLE** [comment]
last 12 weeksMast Cell Activation Disorder

5:39 / 2 hours late today.

5:392

**Comment by Qbone03** [comment]
OSI
1629 K St. N.W Suite 300
Washington D.C. 20006
United States
